// -- API ACTIONS TYPES

// -- ACTIONS TYPES
export const SET_LOBBIES = "SET_LOBBIES";
export const SET_PLAYERS = "SET_PLAYERS";
export const SET_CURRENT_PLAYER = "SET_CURRENT_PLAYER";
export const SET_CURRENT_LOBBY = "SET_CURRENT_LOBBY";
