// -- API ACTIONS TYPES

// -- ACTIONS TYPES
export const SET_LOBBIES = "SET_LOBBIES";
export const SET_PLAYERS = "SET_PLAYERS";
export const SET_GAMES = "SET_GAMES";
export const SET_CURRENT_PLAYER = "SET_CURRENT_PLAYER";
export const SET_CURRENT_LOBBY = "SET_CURRENT_LOBBY";
export const SET_CURRENT_GAME = "SET_CURRENT_GAME";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const SET_PREPARED_ACTION = "SET_PREPARED_ACTION";
