name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install Dependencies
      run: npm install
      working-directory: conquest-frontend

    # Build the project
    - name: Build
      run: npm run build --if-present
      working-directory: conquest-frontend
